name: RandomRush
version: 1.0
author: Rejomy
load: POSTWORLD

commands:
  randomrush:
    aliases:
      - rr
      - randomr
      - rrush
      - randrush
      - randr

softdepend:
  - multiverse-core
  - multiworld
  - My_Worlds
  - placeholderapi

main: me.rejomy.randomrush.RandomRush
api-version: 1.13



